spring:
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      #      uri: mongodb://admin:admin@mongo:27017/offers
      #      uri: mongodb://${MONGO_USER}:${MONGO_PASSWOgRD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
      uri: mongodb://admin:admin@localhost:27017/offers
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63792}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


offer:
  http:
    client:
      config:
        connectionTimeout: 1000
        readTimeout: 1000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        port: 5057
  scheduler:
    request:
      delay: PT3H


scheduling:
  enabled: true

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend


server:
  port: 8000